### ISSUE TITLE
"Input string was not in a correct format" when using the stats component and all stats are 0

### ISSUE THREAD

**Issue by digitalpacman** [mausch/SolrNet#205]
I have checked with .4 and older versions that with the new version of Solr it changed the way it reacts to stats properties when the values are all 0.  Before Solr used to return "```<null name=XXXX/>```.

This difference is somewhere between Solr 5 and Solr 5.2

Now Solr returns this:

```
<lst name="Pricing">
<null name="min"/>
<null name="max"/>
<long name="count">0</long>
<long name="missing">0</long>
<double name="sum">0.0</double>
<double name="sumOfSquares">0.0</double>
<double name="mean">NaN</double>
<double name="stddev">0.0</double>
</lst>
```
When this comes back, with all 0s, SolrNet throws "Input string was not in a correct format".
```
   at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at System.Double.Parse(String s, NumberStyles style, IFormatProvider provider)
   at SolrNet.Impl.ResponseParsers.StatsResponseParser`1.ParseStatsNode(XElement node) in c:\prg\SolrNet\SolrNet\Impl\ResponseParsers\StatsResponseParser.cs:line 73
   at SolrNet.Impl.ResponseParsers.StatsResponseParser`1.ParseStats(XElement node, String selector) in c:\prg\SolrNet\SolrNet\Impl\ResponseParsers\StatsResponseParser.cs:line 52
   at SolrNet.Impl.ResponseParsers.StatsResponseParser`1.Parse(XDocument xml, SolrQueryResults`1 results) in c:\prg\SolrNet\SolrNet\Impl\ResponseParsers\StatsResponseParser.cs:line 38
   at SolrNet.Impl.ResponseParsers.StatsResponseParser`1.<>c__DisplayClass0.<Parse>b__2(SolrQueryResults`1 r) in c:\prg\SolrNet\SolrNet\Impl\ResponseParsers\StatsResponseParser.cs:line 31
   at SolrNet.Utils.F.<>c__DisplayClass0`1.<ToFunc>b__2(T x) in c:\prg\SolrNet\SolrNet\Utils\Unit.cs:line 28
   at SolrNet.SolrQueryResults`1.Switch[R](Func`2 query, Func`2 moreLikeThis) in c:\prg\SolrNet\SolrNet\SolrQueryResults.cs:line 80
   at SolrNet.Impl.AbstractSolrQueryResults`1.Switch(Action`1 query, Action`1 moreLikeThis) in c:\prg\SolrNet\SolrNet\Impl\AbstractSolrQueryResults.cs:line 64
   at SolrNet.Impl.ResponseParsers.StatsResponseParser`1.Parse(XDocument xml, AbstractSolrQueryResults`1 results) in c:\prg\SolrNet\SolrNet\Impl\ResponseParsers\StatsResponseParser.cs:line 31
   at SolrNet.Impl.ResponseParsers.AggregateResponseParser`1.Parse(XDocument xml, AbstractSolrQueryResults`1 results) in c:\prg\SolrNet\SolrNet\Impl\ResponseParsers\AggregateResponseParser.cs:line 15
   at SolrNet.Impl.ResponseParsers.DefaultResponseParser`1.Parse(XDocument xml, AbstractSolrQueryResults`1 results) in c:\prg\SolrNet\SolrNet\Impl\ResponseParsers\DefaultResponseParser.cs:line 27
   at SolrNet.Impl.SolrQueryExecuter`1.Execute(ISolrQuery q, QueryOptions options) in c:\prg\SolrNet\SolrNet\Impl\SolrQueryExecuter.cs:line 545
   at SolrNet.Impl.SolrBasicServer`1.Query(ISolrQuery query, QueryOptions options) in c:\prg\SolrNet\SolrNet\Impl\SolrBasicServer.cs:line 92
   at SolrNet.Impl.SolrServer`1.Query(ISolrQuery query, QueryOptions options) in c:\prg\SolrNet\SolrNet\Impl\SolrServer.cs:line 49
   at UserQuery.Main()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by mausch** [comment]
Fixed in https://github.com/mausch/SolrNet/pull/206

**Comment by mausch** [comment]
@digitalpacman  this should be fixed in https://www.nuget.org/packages/SolrNet/0.5.0-alpha2

**Comment by digitalpacman** [comment]
Fixed in alpha2. Awesome! We're going to switch our nuget to that.
