### ISSUE TITLE
AbstractMethodError

### ISSUE THREAD

**Issue by JDSBCC** [mausch/SolrNet#234]
Hi,

I already add

`<lib dir="../../../contrib/extraction/lib" regex=".*\.jar" />
<lib dir="../../../dist/" regex="solr-cell-\d.*\.jar" />`

and

`<requestHandler name="/update/extract" 
                  startup="lazy"
                  class="solr.extraction.ExtractingRequestHandler" >
		<lst name="defaults">
			<str name="lowernames">true</str>
			<str name="uprefix">ignored_</str>
			<str name="captureAttr">true</str>
			<str name="fmap.a">ignored_</str>
			<str name="fmap.div">ignored_</str>
			<str name="fmap.content">value</str>
			
		</lst>
	</requestHandler>`

to solrconfig.xml, however when I run my program i get this error:

java.lang.RuntimeException: java.lang.AbstractMethodError

	at org.apache.solr.servlet.HttpSolrCall.sendError(HttpSolrCall.java:604)

	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:473)

	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:225)

	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:183)

	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652)

	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)

	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:577)

	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:223)

	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)

	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)

	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)

	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)

	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)

	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)

	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)

	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)

	at org.eclipse.jetty.server.Server.handle(Server.java:499)

	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310)

	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257)

	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)

	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)

	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)

	at java.lang.Thread.run(Thread.java:745)

Caused by: java.lang.AbstractMethodError

	at org.apache.solr.handler.ContentStreamHandlerBase.handleRequestBody(ContentStreamHandlerBase.java:58)

	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:155)

	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2082)

	at org.apache.solr.servlet.HttpSolrCall.execute(HttpSolrCall.java:670)

	at org.apache.solr.servlet.HttpSolrCall.call(HttpSolrCall.java:458)

	... 22 more

What am I doing wrong?

Thanks

**Comment by mausch** [comment]
Hi, this project is about a .NET client for Solr. Your issue is about the Solr server. Please post it to the Solr mailing list http://lucene.apache.org/solr/resources.html#community

**Comment by JDSBCC** [comment]
I think I didnt explain me well xD
Im building a project using solrnet and when I try to extract data from a pdf I got the error showed before.

Here is my code:

```
using (MemoryStream stream = new MemoryStream((byte[])dataReader["file_stream"]))
                    {
                        var solr = ServiceLocator.Current.GetInstance<ISolrOperations<Contribution>>();
                        ExtractParameters extract = new ExtractParameters(stream, "doc1", dataReader["nome_original"] + "")
                        {
                            ExtractOnly = true,
                            ExtractFormat = ExtractFormat.Text
                        };
                        var response = solr.Extract(extract);
                        Debug.WriteLine("\n+++++++++++++++++++++++++++++++ " + response.Content);
                    }
```

**Comment by mausch** [comment]
Hi, that still seems to be an issue with your Solr instance and not with SolrNet. The error message seems to indicate that the extraction/Tika JARs are not correctly installed. Please post this to a Solr mailing list.
Also last I checked there was an issue with content-type detection so you might want to try setting an explicit content-type in your SolrNet call.

**Comment by JDSBCC** [comment]
Thank you, it works. Yes, it was a bad installation of JARS. I had them in duplicate (just different versions) and solr was not working well with it. And sorry for posting in the wrong place =)
